
apiVersion: v1
kind: PersistentVolume
metadata:
  name: office-staff-volume
spec:
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteOnce
  storageClassName: standard # this would be provided by your Cloud provider! you can check available classes via `kubectl get sc`
  hostPath:
    path: "/home/docker/theOffice/"
  # volumeMode: FileSystem # default
  # persistentVolumeReclaimPolicy: Retain # default

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: office-staff-pvc
spec:
  resources:
    requests:
      storage: "100Mi"
  # volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
