apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-staff-server-dep
spec:
  selector:
    matchLabels:
      app: office-staff-server-pod
  template:
    metadata:
      labels:
        app: office-staff-server-pod
    spec:
      volumes:
        - name: empl-vol
          persistentVolumeClaim:
            claimName: office-staff-pvc
      containers:
        - name: office-staff-server
          image: alpine:latest
          command: [
            "/bin/sh",
            "-c",
            "cat /office/staff/staff.txt; sleep 3600"
          ]
          volumeMounts:
            - mountPath: "/office/staff"
              name: empl-vol
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: office-staff-pvc
spec:
  resources:
    requests:
      storage: "100Mi"
  # volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
