apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod-def
  labels:
    name: hello-world-pod
    app: hello-world-pod
spec:
  containers:
    - name: hello-world-container
      image: darshah/k8s_learn:v1
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "10Mi"
      ports:
        - containerPort: 80
