apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - sleep
        - "4800"
      securityContext:
        runAsUser: 2405
        capabilities:
          add: ["SYS_TIME", "NET_ADMIN"]